// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBshwVZfQuCTb5KXe-rc_jZUVoHKxgj2-M',
    appId: '1:414390679869:android:079232247c9e87c2196d54',
    messagingSenderId: '414390679869',
    projectId: 'quizapp-549e1',
    storageBucket: 'quizapp-549e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqiEhg8U56nt-Ry1nvmeRYiJKBHb9hGv4',
    appId: '1:414390679869:ios:fb27d07669cd7de2196d54',
    messagingSenderId: '414390679869',
    projectId: 'quizapp-549e1',
    storageBucket: 'quizapp-549e1.appspot.com',
    iosBundleId: 'io.pranawww.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqiEhg8U56nt-Ry1nvmeRYiJKBHb9hGv4',
    appId: '1:414390679869:ios:fb27d07669cd7de2196d54',
    messagingSenderId: '414390679869',
    projectId: 'quizapp-549e1',
    storageBucket: 'quizapp-549e1.appspot.com',
    iosBundleId: 'io.pranawww.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXmIxfCc4fFst_71njHXXyzCUa29xMtCI',
    appId: '1:414390679869:web:a71e17072738ce32196d54',
    messagingSenderId: '414390679869',
    projectId: 'quizapp-549e1',
    authDomain: 'quizapp-549e1.firebaseapp.com',
    storageBucket: 'quizapp-549e1.appspot.com',
  );
}
